<a href="https://colab.research.google.com/github/shailendra-repo/Machine-Learning-with-Python-From-Linear-Models-to-Deep-Learning/blob/main/Assignments_001.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
def randomization(n):
    """
    Arg:
      n - an integer
    Returns:
      A - a randomly-generated nx1 Numpy array.
    """
    #Your code here
    A = np.random.random([n,1])
    return A
    raise NotImplementedError

In [3]:
randomization(5)

array([[0.26559394],
       [0.82154843],
       [0.79052744],
       [0.43123536],
       [0.41096106]])

In [4]:
a1 = randomization(5)

In [5]:
a1.size

5

In [6]:
a1.shape

(5, 1)

In [7]:
def operations(h, w):
    """
    Takes two inputs, h and w, and makes two Numpy arrays A and B of size
    h x w, and returns A, B, and s, the sum of A and B.

    Arg:
      h - an integer describing the height of A and B
      w - an integer describing the width of A and B
    Returns (in this order):
      A - a randomly-generated h x w Numpy array.
      B - a randomly-generated h x w Numpy array.
      s - the sum of A and B.
    """
    #Your code here
    A = np.random.random([h,w])
    B = np.random.random([h,w])
    s = A + B
    return A,B,s

    raise NotImplementedError

In [8]:
operations(2,3)

(array([[0.55012715, 0.64958907, 0.85889918],
        [0.10442   , 0.59592469, 0.9767754 ]]),
 array([[0.6458408 , 0.73495771, 0.84194706],
        [0.792572  , 0.60722921, 0.86062468]]),
 array([[1.19596796, 1.38454678, 1.70084624],
        [0.896992  , 1.2031539 , 1.83740008]]))

In [17]:
def norm(h, w):
    """
    Takes two inputs, h and w, and makes two Numpy arrays A and B of size
    h x w, and returns A, B, and s, the sum of A and B.

    Arg:
      h - an integer describing the height of A and B
      w - an integer describing the width of A and B
    Returns (in this order):
      A - a randomly-generated h x w Numpy array.
      B - a randomly-generated h x w Numpy array.
      s - the sum of A and B.
    """
    #Your code here
    A = np.random.random([h,w])
    B = np.random.random([h,w])
    s = A + B
    L2 = np.linalg.norm(s)
    return A,B,s,L2

    raise NotImplementedError

In [18]:
norm(2,3)

(array([[0.37610526, 0.32712363, 0.28562101],
        [0.76943665, 0.50483364, 0.28490172]]),
 array([[0.03561988, 0.9815642 , 0.48742292],
        [0.46679563, 0.85478917, 0.92836326]]),
 array([[0.41172514, 1.30868783, 0.77304393],
        [1.23623228, 1.35962282, 1.21326499]]),
 2.7071451265475552)

In [30]:
def neural_network(inputs, weights):
    """
     Takes an input vector and runs it through a 1-layer neural network
     with a given weight matrix and returns the output.

     Arg:
       inputs - 2 x 1 NumPy array
       weights - 2 x 1 NumPy array
     Returns (in this order):
       out - a 1 x 1 NumPy array, representing the output of the neural network
    """
    tmp = inputs * weights
    z = np.tanh(tmp.sum())
    return z

    #Your code here
    raise NotImplementedError


In [31]:
neural_network(np.random.random([2,1]),np.random.random([2,1]))

0.25261804181855635

In [26]:
inputs = np.array([2,5])
weights = np.array([3,6])

In [27]:
tmp = inputs * weights

In [28]:
tmp

array([ 6, 30])

In [29]:
tmp.sum()

36

In [32]:
ot = np.tanh(tmp.sum())

In [33]:
type(ot)

numpy.float64

In [35]:
f = np.array(ot)

In [36]:
type(f)

numpy.ndarray

In [37]:
ot

1.0

In [44]:
weights1 = np.array([[0.60198498], [0.48975768]])
inputs1 = np.array([[0.23286057], [0.06406987]])
#Submission output: [[0.16989377]]

In [45]:
def neural_network(inputs, weights):
    """
     Takes an input vector and runs it through a 1-layer neural network
     with a given weight matrix and returns the output.

     Arg:
       inputs - 2 x 1 NumPy array
       weights - 2 x 1 NumPy array
     Returns (in this order):
       out - a 1 x 1 NumPy array, representing the output of the neural network
    """
    tmp = inputs * weights
    z = np.tanh(tmp.sum())
    return np.array([[z]])

    #Your code here
    raise NotImplementedError


In [46]:
neural_network(inputs1, weights1)

array([[0.16989377]])

In [47]:
def scalar_function(x, y):
    """
    Returns the f(x,y) defined in the problem statement.
    """
    #Your code here

    if x <= y:
      z = x * y
    else:
      z = x / y
    return z
          
    raise NotImplementedError

In [48]:
scalar_function(3,4)

12

In [49]:
scalar_function(4,3)

1.3333333333333333

In [50]:
vec_function = np.vectorize(scalar_function)

In [51]:
vec_function([1,2,3],[4,5,6])

array([ 4, 10, 18])

In [56]:
vec_function([2,4],[3,3])

array([6, 1])

In [78]:
a1 = np.array([2,3,4])
a2 = np.array([3,4,3]) 

In [59]:
a1[a1 <= a2]

array([2])

In [60]:
print(a1[a1 <= a2])

[2]


In [80]:
cmp = a1 <= a2

In [63]:
cmp

array([ True, False])

In [64]:
a1[cmp]

array([2])

In [65]:
a2[cmp]

array([3])

In [74]:
z= np.array([cmp.size])


In [75]:
z

array([2])

In [84]:
 a1[cmp == True] * a2[cmp == True]
 #a1[cmp == False] / a2[cmp == False]

array([ 6, 12])

In [87]:
a1 = np.array([2,4,3])
a2 = np.array([3,3,4]) 

cmp = a1 <= a2
z = np.array(cmp.size)
a1[cmp == True] * a2[cmp == True]

array([ 6, 12])

In [96]:
z[cmp == True]  = a1[cmp == True] * a2[cmp == True]

In [97]:
z

array([ 6.,  0., 12.])

In [91]:
cmp.size

3

In [94]:
z = np.zeros(cmp.size)

In [95]:
z.size

3

In [98]:
def vector_function(x, y):
    """
    Make sure vector_function can deal with vector input x,y 
    """
    #Your code here

    cmp = x <= y
    z = np.zeros(cmp.size)
    z[cmp == True] = x[cmp == True]  * y[cmp == True]
    z[cmp == False] = x[cmp == False]  / y[cmp == False]

    return z

    raise NotImplementedError


In [100]:
vector_function(np.array([2,6]),np.array([4,5]))

array([8. , 1.2])