<a href="https://colab.research.google.com/github/shailendra-repo/Python/blob/main/Intro_to_pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# Introduction to Pandas


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt


In [3]:
pd.set_option('display.max_columns',10)
pd.set_option('display.max_rows',10)
pd.set_option('display.notebook_repr_html',False)


In [4]:
df = pd.DataFrame([1,2,3,4])

In [5]:
df

   0
0  1
1  2
2  3
3  4

### Lesson 2

In [9]:
np.random.seed(1)
s = pd.Series(np.random.randn(100))
s

0     1.624345
1    -0.611756
2    -0.528172
3    -1.072969
4     0.865408
        ...   
95    0.077340
96   -0.343854
97    0.043597
98   -0.620001
99    0.698032
Length: 100, dtype: float64

In [10]:
s[2]

-0.5281717522634557

In [11]:
s[[2,4,6]]

2   -0.528172
4    0.865408
6    1.744812
dtype: float64

In [12]:
s[3:8]

3   -1.072969
4    0.865408
5   -2.301539
6    1.744812
7   -0.761207
dtype: float64

In [13]:
s.head()

0    1.624345
1   -0.611756
2   -0.528172
3   -1.072969
4    0.865408
dtype: float64

In [14]:
s.tail()

95    0.077340
96   -0.343854
97    0.043597
98   -0.620001
99    0.698032
dtype: float64

In [19]:
list(s.index)

[0,
 1,
 2,
 3,
 4,
 5,
 6,
 7,
 8,
 9,
 10,
 11,
 12,
 13,
 14,
 15,
 16,
 17,
 18,
 19,
 20,
 21,
 22,
 23,
 24,
 25,
 26,
 27,
 28,
 29,
 30,
 31,
 32,
 33,
 34,
 35,
 36,
 37,
 38,
 39,
 40,
 41,
 42,
 43,
 44,
 45,
 46,
 47,
 48,
 49,
 50,
 51,
 52,
 53,
 54,
 55,
 56,
 57,
 58,
 59,
 60,
 61,
 62,
 63,
 64,
 65,
 66,
 67,
 68,
 69,
 70,
 71,
 72,
 73,
 74,
 75,
 76,
 77,
 78,
 79,
 80,
 81,
 82,
 83,
 84,
 85,
 86,
 87,
 88,
 89,
 90,
 91,
 92,
 93,
 94,
 95,
 96,
 97,
 98,
 99]

In [20]:
s.values

array([ 1.62434536, -0.61175641, -0.52817175, -1.07296862,  0.86540763,
       -2.3015387 ,  1.74481176, -0.7612069 ,  0.3190391 , -0.24937038,
        1.46210794, -2.06014071, -0.3224172 , -0.38405435,  1.13376944,
       -1.09989127, -0.17242821, -0.87785842,  0.04221375,  0.58281521,
       -1.10061918,  1.14472371,  0.90159072,  0.50249434,  0.90085595,
       -0.68372786, -0.12289023, -0.93576943, -0.26788808,  0.53035547,
       -0.69166075, -0.39675353, -0.6871727 , -0.84520564, -0.67124613,
       -0.0126646 , -1.11731035,  0.2344157 ,  1.65980218,  0.74204416,
       -0.19183555, -0.88762896, -0.74715829,  1.6924546 ,  0.05080775,
       -0.63699565,  0.19091548,  2.10025514,  0.12015895,  0.61720311,
        0.30017032, -0.35224985, -1.1425182 , -0.34934272, -0.20889423,
        0.58662319,  0.83898341,  0.93110208,  0.28558733,  0.88514116,
       -0.75439794,  1.25286816,  0.51292982, -0.29809284,  0.48851815,
       -0.07557171,  1.13162939,  1.51981682,  2.18557541, -1.39

In [21]:
s2 = pd.Series([1,2,3,4], index=['a','b','c','d'])
s2

a    1
b    2
c    3
d    4
dtype: int64

In [23]:
s3 = pd.Series({'a':1, 'b':2, 'c': 3})
s3

a    1
b    2
c    3
dtype: int64

In [24]:
s3.index

Index(['a', 'b', 'c'], dtype='object')

# Shape, Size, uniquness and counts of values

In [25]:
s = pd.Series([5, 0, 1, 1, 2, 3, 4, 5, 6, np.nan])
s

0    5.0
1    0.0
2    1.0
3    1.0
4    2.0
5    3.0
6    4.0
7    5.0
8    6.0
9    NaN
dtype: float64

In [26]:
len(s)

10

In [27]:
s.shape

(10,)

In [28]:
s.count()

9

In [29]:
s.unique()

array([ 5.,  0.,  1.,  2.,  3.,  4.,  6., nan])

In [31]:
s.value_counts()

1.0    2
5.0    2
6.0    1
4.0    1
3.0    1
2.0    1
0.0    1
dtype: int64

# Alignment via index labels

In [32]:
s3 = pd.Series([1, 2, 3, 4], index=['a', 'b', 'c', 'd'])
s3

a    1
b    2
c    3
d    4
dtype: int64

In [33]:
s4 = pd.Series([4, 3, 2, 1], index=['d', 'c', 'b', 'a'])
s4

d    4
c    3
b    2
a    1
dtype: int64

In [34]:
s3+s4

a    2
b    4
c    6
d    8
dtype: int64

In [35]:
a1 = np.array([1, 2, 3, 4])
a2 = np.array([4, 3, 2, 1])
a1+a2

array([5, 5, 5, 5])

# **Creating a DataFrame**

In [38]:
pd.DataFrame(np.array([[10,11],[20,21]]))

    0   1
0  10  11
1  20  21

In [39]:
df1 = pd.DataFrame([pd.Series(np.arange(10,15)), pd.Series(np.arange(15,20))])
df1

    0   1   2   3   4
0  10  11  12  13  14
1  15  16  17  18  19

In [40]:
df1.shape

(2, 5)

In [41]:
df = pd.DataFrame(np.array([[10,11],[20,21]]), columns=['a','b'])

In [42]:
df

    a   b
0  10  11
1  20  21

In [43]:
df.columns

Index(['a', 'b'], dtype='object')

In [44]:
df.columns = ['c1','c2']
df

   c1  c2
0  10  11
1  20  21

In [53]:
df = pd.DataFrame(np.array([[0,1],[2,3]]), columns=['c1','c2'],  index=['r1','r2'])

In [55]:
df

    c1  c2
r1   0   1
r2   2   3

In [56]:
df.index

Index(['r1', 'r2'], dtype='object')

In [57]:
df.values

array([[0, 1],
       [2, 3]])

In [58]:
s1 = pd.Series(np.arange(1,6,1))
s2 = pd.Series(np.arange(6,11,1))
pd.DataFrame({'c1':s1, 'c2':s2})

   c1  c2
0   1   6
1   2   7
2   3   8
3   4   9
4   5  10

In [59]:
s3 = pd.Series(np.arange(12,14), index=[1,2])

In [62]:
pd.DataFrame({'c1':s1,'c2':s2, 'c3':s3})

   c1  c2    c3
0   1   6   NaN
1   2   7  12.0
2   3   8  13.0
3   4   9   NaN
4   5  10   NaN

## Example data

In [67]:
sp500 = pd.read_csv('sp500.csv', index_col='Symbol', usecols=[0,2,3,7])

In [68]:
sp500.head()

                        Sector   Price  Book Value
Symbol                                            
MMM                Industrials  141.14      26.668
ABT                Health Care   39.60      15.573
ABBV               Health Care   53.95       2.954
ACN     Information Technology   79.79       8.326
ACE                 Financials  102.91      86.897

In [69]:
sp500.index

Index(['MMM', 'ABT', 'ABBV', 'ACN', 'ACE', 'ACT', 'ADBE', 'AES', 'AET', 'AFL',
       ...
       'XEL', 'XRX', 'XLNX', 'XL', 'XYL', 'YHOO', 'YUM', 'ZMH', 'ZION', 'ZTS'],
      dtype='object', name='Symbol', length=500)

## Selecting columns of a DataFrame

In [80]:
sp500[:2][:1]

             Sector   Price  Book Value
Symbol                                 
MMM     Industrials  141.14      26.668

In [83]:
sp500['Price']

Symbol
MMM     141.14
ABT      39.60
ABBV     53.95
ACN      79.79
ACE     102.91
         ...  
YHOO     35.02
YUM      74.77
ZMH     101.84
ZION     28.43
ZTS      30.53
Name: Price, Length: 500, dtype: float64

In [85]:
sp500.columns

Index(['Sector', 'Price', 'Book Value'], dtype='object')

In [88]:
sp500[['Price','Book Value']].head(2)

         Price  Book Value
Symbol                    
MMM     141.14      26.668
ABT      39.60      15.573

In [89]:
sp500.Price

Symbol
MMM     141.14
ABT      39.60
ABBV     53.95
ACN      79.79
ACE     102.91
         ...  
YHOO     35.02
YUM      74.77
ZMH     101.84
ZION     28.43
ZTS      30.53
Name: Price, Length: 500, dtype: float64

## Selecting rows of a DataFrame

In [90]:
sp500[:3]

             Sector   Price  Book Value
Symbol                                 
MMM     Industrials  141.14      26.668
ABT     Health Care   39.60      15.573
ABBV    Health Care   53.95       2.954

In [91]:
sp500['XYL':'YUM']

                        Sector  Price  Book Value
Symbol                                           
XYL                Industrials  38.42      12.127
YHOO    Information Technology  35.02      12.768
YUM     Consumer Discretionary  74.77       5.147

In [93]:
sp500.loc['MMM']

Sector        Industrials
Price              141.14
Book Value         26.668
Name: MMM, dtype: object

In [96]:
sp500.loc[['MMM','MSFT']]

                        Sector   Price  Book Value
Symbol                                            
MMM                Industrials  141.14      26.668
MSFT    Information Technology   40.12      10.584

In [97]:
sp500.iloc[[0,2]]

             Sector   Price  Book Value
Symbol                                 
MMM     Industrials  141.14      26.668
ABBV    Health Care   53.95       2.954

In [99]:
i1 = sp500.index.get_loc('MMM')
i2 = sp500.index.get_loc('A')

In [102]:
sp500.iloc[[i1,i2]]

             Sector   Price  Book Value
Symbol                                 
MMM     Industrials  141.14      26.668
A       Health Care   56.18      16.928

## Selecting rows by index label and/or location: .ix[]

In [104]:
sp500.ix[['MSFT', 'ZTS']]

AttributeError: ignored

In [105]:
sp500.at['MMM', 'Price']

141.14

In [107]:
sp500.iat[0,1]

141.14

In [109]:
sp500[sp500.Price < 100]

                        Sector  Price  Book Value
Symbol                                           
ABT                Health Care  39.60      15.573
ABBV               Health Care  53.95       2.954
ACN     Information Technology  79.79       8.326
ADBE    Information Technology  64.30      13.262
AES                  Utilities  13.61       5.781
...                        ...    ...         ...
XYL                Industrials  38.42      12.127
YHOO    Information Technology  35.02      12.768
YUM     Consumer Discretionary  74.77       5.147
ZION                Financials  28.43      30.191
ZTS                Health Care  30.53       2.150

[407 rows x 3 columns]

In [112]:
sp500[(sp500.Price < 10) & (sp500.Price > 0)]

                             Sector  Price  Book Value
Symbol                                                
FTR     Telecommunications Services   5.81       3.989
HCBK                     Financials   9.80       9.596
HBAN                     Financials   9.10       6.995
SLM                      Financials   8.82      11.895
WIN     Telecommunications Services   9.38       1.199

## Arithmetic on a DataFrame¶

In [117]:
np.random.seed(1)
df = pd.DataFrame(np.random.randn(5,4),columns=['A','B','C','D'])

In [118]:
df

          A         B         C         D
0  1.624345 -0.611756 -0.528172 -1.072969
1  0.865408 -2.301539  1.744812 -0.761207
2  0.319039 -0.249370  1.462108 -2.060141
3 -0.322417 -0.384054  1.133769 -1.099891
4 -0.172428 -0.877858  0.042214  0.582815

In [119]:
df*2

          A         B         C         D
0  3.248691 -1.223513 -1.056344 -2.145937
1  1.730815 -4.603077  3.489624 -1.522414
2  0.638078 -0.498741  2.924216 -4.120281
3 -0.644834 -0.768109  2.267539 -2.199783
4 -0.344856 -1.755717  0.084427  1.165630

In [120]:
df - df.iloc[0]

          A         B         C         D
0  0.000000  0.000000  0.000000  0.000000
1 -0.758938 -1.689782  2.272984  0.311762
2 -1.305306  0.362386  1.990280 -0.987172
3 -1.946763  0.227702  1.661941 -0.026923
4 -1.796774 -0.266102  0.570385  1.655784

In [121]:
subframe = df[1:4][['B','C']]

In [123]:
subframe

          B         C
1 -2.301539  1.744812
2 -0.249370  1.462108
3 -0.384054  1.133769

In [124]:
df - subframe

    A    B    C   D
0 NaN  NaN  NaN NaN
1 NaN  0.0  0.0 NaN
2 NaN  0.0  0.0 NaN
3 NaN  0.0  0.0 NaN
4 NaN  NaN  NaN NaN

In [126]:
a_col = df['A']

In [127]:
df.sub(a_col, axis=0)

     A         B         C         D
0  0.0 -2.236102 -2.152517 -2.697314
1  0.0 -3.166946  0.879404 -1.626615
2  0.0 -0.568409  1.143069 -2.379180
3  0.0 -0.061637  1.456187 -0.777474
4  0.0 -0.705430  0.214642  0.755243

## Reindexing Series and DataFrame objects

In [128]:
np.random.seed(1)
s = pd.Series(np.random.randn(5))

In [129]:
s

0    1.624345
1   -0.611756
2   -0.528172
3   -1.072969
4    0.865408
dtype: float64

In [130]:
s.index

RangeIndex(start=0, stop=5, step=1)

In [132]:
s.index = ['a','b','c','d','e']

In [133]:
s

a    1.624345
b   -0.611756
c   -0.528172
d   -1.072969
e    0.865408
dtype: float64

In [134]:
s2 = s.reindex(['a','c','d','e'])

In [135]:
s2

a    1.624345
c   -0.528172
d   -1.072969
e    0.865408
dtype: float64

In [136]:
s2['a'] = 0

In [137]:
s2

a    0.000000
c   -0.528172
d   -1.072969
e    0.865408
dtype: float64

In [138]:
s['a']

1.6243453636632417

In [139]:
# Series objects with string and integer index types
# with the "same" values will not align
s1 = pd.Series([0, 1, 2], index=[0, 1, 2])
s2 = pd.Series([3, 4, 5], index=['0', '1', '2'])
s1 + s2

0   NaN
1   NaN
2   NaN
0   NaN
1   NaN
2   NaN
dtype: float64

In [140]:
# demonstrate treating values at a specific type
s2.index = s2.index.values.astype(int)
s1 + s2

0    3
1    5
2    7
dtype: int64

In [141]:
# show reindexing with filling of NaN with a specified value
s2 = s.copy()
s2.reindex(['a', 'f'], fill_value=0)

a    1.624345
f    0.000000
dtype: float64

In [142]:
# a Series to demonstrate reindexing
s3 = pd.Series(['red', 'green', 'blue'], index=[0, 3, 5])
s3

0      red
3    green
5     blue
dtype: object

In [143]:
# forward fill (last known value technique)
s3.reindex(np.arange(0,7), method='ffill')

0      red
1      red
2      red
3    green
4    green
5     blue
6     blue
dtype: object

In [144]:
# demonstrate how backwards fill differs
s3.reindex(np.arange(0,7), method='bfill')

0      red
1    green
2    green
3    green
4     blue
5     blue
6      NaN
dtype: object