<a href="https://colab.research.google.com/github/shailendra-repo/Machine-Learning-with-Python-From-Linear-Models-to-Deep-Learning/blob/main/Unit%200.%20Brief%20Prerequisite%20Reviews%2C%20Homework%200%2C%20and%20Project%200.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pdb

In [2]:
pdb.set_trace()



PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check: 
http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
to see how to restore the debug tracing back correctly.
Call Location:
  File "/usr/lib/python3.7/bdb.py", line 332, in set_trace
    sys.settrace(self.trace_dispatch)



--Call--
> /usr/local/lib/python3.7/dist-packages/IPython/core/displayhook.py(236)__call__()
-> def __call__(self, result=None):
(Pdb) x=200
(Pdb) x*5
1000
(Pdb) exit()



PYDEV DEBUGGER WARNING:
sys.settrace() should not be used when the debugger is being used.
This may cause the debugger to stop working correctly.
If this is needed, please check: 
http://pydev.blogspot.com/2007/06/why-cant-pydev-debugger-work-with.html
to see how to restore the debug tracing back correctly.
Call Location:
  File "/usr/lib/python3.7/bdb.py", line 357, in set_quit
    sys.settrace(None)



BdbQuit: ignored

In [25]:

def get_sum_metrics(predictions, metrics=[]):
    
    for i in range(3):
        metrics.append(lambda x: x + i)

    sum_metrics = 0
    for metric in metrics:
        sum_metrics += metric(predictions)

    return sum_metrics


In [6]:
import numpy as np
num = np.array([3,4,5,6])

In [12]:
get_sum_metrics(num,[np.sum,np.mean])

array([37.5, 40.5, 43.5, 46.5])

In [15]:
get_sum_metrics(num)

> <ipython-input-14-38912238a5f1>(4)get_sum_metrics()
-> for i in range(3):
(Pdb) metrics
[]
(Pdb) n
> <ipython-input-14-38912238a5f1>(5)get_sum_metrics()
-> metrics.append(lambda x: x + i)
(Pdb) n
> <ipython-input-14-38912238a5f1>(4)get_sum_metrics()
-> for i in range(3):
(Pdb) n
> <ipython-input-14-38912238a5f1>(5)get_sum_metrics()
-> metrics.append(lambda x: x + i)
(Pdb) n
> <ipython-input-14-38912238a5f1>(4)get_sum_metrics()
-> for i in range(3):
(Pdb) metrics
[<function get_sum_metrics.<locals>.<lambda> at 0x7f1575b09e60>, <function get_sum_metrics.<locals>.<lambda> at 0x7f1575b09dd0>]
(Pdb) e
*** NameError: name 'e' is not defined
(Pdb) help

Documented commands (type help <topic>):
EOF    c          d        h         list      q        rv       undisplay
a      cl         debug    help      ll        quit     s        unt      
alias  clear      disable  ignore    longlist  r        source   until    
args   commands   display  interact  n         restart  step     up       
b 

BdbQuit: ignored

In [16]:
range(3)

range(0, 3)

In [18]:
for i in range(3):
  print (i)

0
1
2


In [19]:
def create_multipliers():
    return [lambda x : i * x for i in range(5)]

for multiplier in create_multipliers():
    print(multiplier(2))

8
8
8
8
8


In [23]:
def create_multipliers():
    return [lambda x : i * x for i in range(5)]

for multiplier in create_multipliers():
    print('Shailendra')
    print(multiplier(2))

Shailendra
8
Shailendra
8
Shailendra
8
Shailendra
8
Shailendra
8


In [26]:
def create_multipliers():
    return [lambda x, i=i : i * x for i in range(5)]
for multiplier in create_multipliers():
    print('Shailendra')
    print(multiplier(2))

Shailendra
0
Shailendra
2
Shailendra
4
Shailendra
6
Shailendra
8


In [31]:
get_sum_metrics(np.array([1,2]))

array([6, 9])

In [33]:

def get_sum_metrics(predictions, metrics=[]):
    
    for i in range(3):
        metrics.append(lambda x, i=i: x + i)

    sum_metrics = 0
    for metric in metrics:
        sum_metrics += metric(predictions)

    return sum_metrics

In [84]:
def get_sum_metrics(predictions, metrics=None):
    if metrics is None:
      metrics=[]
      
    for i in range(3):
        metrics.append(lambda x , i=i: x + i)

    sum_metrics = 0
    for metric in metrics:
        sum_metrics += metric(predictions)

    return sum_metrics

In [86]:
get_sum_metrics(np.array([0,1,2,3]))

array([ 3,  6,  9, 12])

In [82]:
def append_to(element, to=None):
    if to is None:
      to = []
    to.append(element)
    return to

In [83]:
my_list = append_to(12)
print(my_list)

my_other_list = append_to(42)
print(my_other_list)

[12]
[42]
